### ISSUE TITLE
[Bug]: The getProducts method is causing an unhandled error when loading product without any taxons on a certain product's page.

### ISSUE THREAD

**Issue by witoldkesek** [vuestorefront/spree#112]
### Expected Behavior

When you go to a certain product's page, the backend uses the getProducts function to the "suggested" products. It should load or skip them them no matter they have any taxons or not. 

### Actual Behavior

The products without taxons cause unhandled errors because the backend tries to parse the taxons no matter they exist or not.

### Possible Solution

It is possible that in the function "buiildBreadcrums" in the file **api-client/src/api/serializers/product.ts** handling addTaxonToBreadcrumbs conditionally if taxons exist will fix the issue.
![image](https://user-images.githubusercontent.com/49924891/154442232-a769d4d2-64f1-402a-97e7-e6ccd2a1a494.png)

### Steps to reproduce

Connect a backend with products that don't have any taxons assigned to them and go to any certain product's page. Following error should appear:
![image](https://user-images.githubusercontent.com/49924891/154432507-3d9e931d-8dae-44fc-913e-e4fdae38ec25.png)

### What version of Spree integration are you using?

1.2.0

### What version of Node.js are you using?

14.17.6

### What browser (and version) are you using?

Brave

### What operating system (and version) are you using?

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdavo6** [comment]
I was experiencing the issue identified above on every page load (including homepage). The suggested solution resolved the issue for me. Thanks @witoldkesek
