### ISSUE TITLE
[Bug]: Checkout - size column displays color

### ISSUE THREAD

**Issue by rafalkosla101** [vuestorefront/spree#144]
### Expected Behavior

Each column displays associated parameter (column: size displays sizes of products, column: color displays colors)

### Actual Behavior

In the checkout proces column size displays a color of an item.

### What version of Spree integration are you using?

1.3.0

### What version of Node.js are you using?

14.18.0

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

macOs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rafalcymerys** [comment]
@rafalkosla101 is that still an issue in the latest version?

**Comment by rafalkosla101** [comment]
it is not or at least I cannot reproduce it, so closing the issue
