### ISSUE TITLE
[Bug]: Shipping/Billing address state/province value always equals to "Alabama" in the admin panel

### ISSUE THREAD

**Issue by letelete** [vuestorefront/spree#159]
### Expected Behavior

State/Province value should equal to the one set up on the client.

### Actual Behavior

Currently, when the order is opened in the Orders tab of the Admin Panel, the value always equals "Alabama".

### Steps to reproduce

1. Add any product to the shopping cart
2. Fill checkout forms with:
    Country: `United States`
    State/Province `California`
4. Order the product
5. Open the admin panel > Orders > <your order> > Customer
6. Verify a value of the "State" field.

### What version of Spree integration are you using?

1.3

### What version of Node.js are you using?

14.19

### What browser (and version) are you using?

Firefox Developers 99.0b3 (64-bit)

### What operating system (and version) are you using?

macOS

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by letelete** [comment]
After @rafalkosla101's investigation, it seems like a backend UI issue. Postman returns valid data. Closing for now.

**Comment by rafalcymerys** [comment]
I'd do another pass of investigation, this feels a bit off. Let me take a look at the backend and see why it breaks
