### ISSUE TITLE
[Feature]: Multi currency support

### ISSUE THREAD

**Issue by rafalcymerys** [vuestorefront/spree#77]
### How the project can be improved?

Spree 4.3 and later support multi-currency out of the box. 
The Spree-VSF integration should take that into consideration and pass the correct currency to API requests

### What are the acceptance criteria?

- [ ] Currency switcher is connected to a cookie
- [ ] API requests to all endpoints include currency code
- [ ] Changing currency in VSF triggers cart currency change via the API
- [ ] A correct currency symbol is displayed on the frontend

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by damianlegawiec** [comment]
@rafalcymerys actually Spree 4.2 also comes with built-in multi-currency :)

**Comment by diegolezana** [comment]
#89

**Comment by rafalcymerys** [comment]
This was implemented in #89
