### ISSUE TITLE
[Feature]: Implement useShippingProvider composable

### ISSUE THREAD

**Issue by rafalcymerys** [vuestorefront/spree#78]
### How the project can be improved?

VSF 2.4.0 introduced `useShippingProvider` composable, that provides methods for managing shipping methods during a checkout.

Currently, the theme interacts directly with the API to pull available shipping methods or to save selection. 
We should migrate to Vue Storefront's model, to keep it consistent and make use of some other VSF mechanisms (like shipping getters).

### What are the acceptance criteria?

- [ ] useShippingProvider composable is implemented
- [ ] Calls to $spree in /pages/Shipping.vue are replaced with useShippingProvider
- [ ] checkoutGetters for shipping are implemented
- [ ] Handling multiple shipments works properly
- [ ] Shipping cost displays correctly in CartPreview.vue (after it's selected during the checkout)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by damianlegawiec** [comment]
Hi @rafalcymerys 

FYI, In Spree v4.4 we'll be adding some new (better) checkout endpoints:

- Create new Payment - https://api.spreecommerce.org/docs/api-v2/b3A6MjYyODA2NTY-create-new-payment
- Select Shipping Method - WIP - we'll be merged this week

So it will be easier to manage these during checkout than using the Checkout Update endpoint

**Comment by rafalcymerys** [comment]
Hi @damianlegawiec - this looks good, I know the old endpoint was a bit confusing.
Will Spree 4.4 still support the /checkout update endpoint as well, for updating payment and shipping?

**Comment by damianlegawiec** [comment]
@rafalcymerys new checkout endpoints are supported now in SDK - https://github.com/spree/spree-storefront-api-v2-js-sdk/releases/tag/v4.12.0
