### ISSUE TITLE
[Feature]: Wishlists support

### ISSUE THREAD

**Issue by rafalcymerys** [vuestorefront/spree#79]
### How the project can be improved?

Spree doesn't provide wishlists out of the box, but there's a popular extension `spree_wishlist` that adds this functionality. 
The integration should allow to optionally enable the `useWishlist` composable to connect to the API exposed by spree_wishlist.

### What are the acceptance criteria?

- [ ] useWishlist composable is implemented
- [ ] Wishlists work for signed-in users
- [ ] A feature flag is available that disables any API calls to the wishlists API (in case someone wants to connect to a Spree instance that doesn't have spree_wishlist installed).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by damianlegawiec** [comment]
@rafalcymerys we've added native wishlists to spree in v4.4 - https://api.spreecommerce.org/docs/api-v2/b3A6MjE0NTY5Mzg-list-all-wishlists

`spree_wishlist` won't be supported in the future

**Comment by damianlegawiec** [comment]
@rafalcymerys https://github.com/spree/spree-storefront-api-v2-js-sdk/releases/tag/v4.12.0 includes wishlists support 🚀
